### ISSUE TITLE
Feature: User can add a resort to the app (using Google Maps)

### ISSUE THREAD

**Issue by heesoo-kim97** [heesoo-kim97/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="611" alt="Screen Shot 2021-10-05 at 10 53 52 AM" src="https://user-images.githubusercontent.com/82424354/136076753-fa0d1146-e3be-4463-b516-f6e2b4d8d7f7.png">
<img width="454" alt="Screen Shot 2021-10-05 at 10 53 35 AM" src="https://user-images.githubusercontent.com/82424354/136076761-fd7e521e-128d-45b8-a699-82ff67b2c017.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create database called skiTrip
- [x] Update `schema.sql` to create table of resorts, trips, and checklistItems
- [ ] From map page component push data into database

### ☁️ Server

- [x] Update `server/index.js` to listen for a POST request from the client
- [ ] Add style to Home Page
     - [ ] set background-color
     - [ ] set text color
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update and import react-bootstrap, google-map apis to app.jsx
- [ ] Create a component to make Home Page
     - [ ] Add ski Image
     - [ ] Add list dropdown icon
     - [ ] Add get started button that takes you to map page
- [ ] Create a component to handle map page 
        - [ ] Update pop-up style
        - [ ] Add 'ADD' button to the pop-up 
        - [ ] using google map search places - get hold of long, lat, address, and country

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
